server:
  port: 9101
aliyun:
  sms:
    accessKeyId: LTAIm84IKu87WWqg
    accessKeySecret: zcrdRYvJ2vWfDYdf6Z5MXG7ypyHH1X
    templateCode: SMS_137670376
    signName: Tree
spring:
  rabbitmq:
    host: 192.168.200.128
